PR templates
Juan-Alejandro-Arriaga/css3 pull request #2
Opened 2024-12-10 23:00 UTC by Juan-Alejandro-Arriaga

Templates para el PR

2024-12-10 23:04 UTC, semanticmx approved these changes
perfecto!

2024-12-17 17:41 UTC, semanticmx requested changes

2024-12-17 17:41 UTC, semanticmx commented on pull_request_template.md
> +* Be concise and to the point
Agrega una instrucción para que se adjunten screenshots para ver la implementación gráficamente.

2025-01-15 03:10 UTC, semanticmx approved these changes
gracias

2025-01-16 16:46 UTC, Carmen-Mercado approved these changes
Muy bien, gracias!

2025-01-20 16:50 UTC, merged